# action.yml
name: "Code Checkstyle"
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: "GITHUB_TOKEN. GitHub CLI is preinstalled on all GitHub-hosted runners. For each step that uses GitHub CLI, you must set an environment variable called GITHUB_TOKEN to a token with the required scopes."
    default: ${{ github.token }}
    required: true
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  ### Flags for reviewdog ###
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    required: false
    default: 'reviewdog'
  level:
    description: "Report level for reviewdog [info, warning, error]"
    required: false
    default: "info"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
    required: false
    default: "added"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true, false]
    required: false
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    required: false
    default: ""
  reviewdog_version:
    description: |
      reviewdog version to be used during code analysis
    required: false
    default: "v0.14.1"
  ### Flags for checkstyle ###
  checkstyle_config:
    description: |
      Checkstyle is highly configurable and can be made to support almost any coding standard. 
      An example configuration files are supplied supporting the Sun Code Conventions, Google Java Style.
    required: true
    default: "google_checks.xml"
  checkstyle_version:
    description: |
      Checkstyle version to be used during analysis.
      For a list of available version numbers go to [Checkstyle release page](https://github.com/checkstyle/checkstyle/releases/).
    required: false
    default: "10.3"
  review_secret:
    description: "REPO_SECRET"
    required: true
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        CHECKSTYLE_VERSION: ${{ inputs.checkstyle_version }}
        REVIEWDOG_VERSION: ${{ inputs.reviewdog_version }}
        INPUT_CHECKSTYLE_CONFIG: ${{ inputs.checkstyle_config }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        PAT: ${{ inputs.review_secret }}
